author   = "Sukr Contributors"
base_url = "https://sukr.io"
title    = "Sukr Documentation"

[paths]
content   = "content"
output    = "public"
static    = "static"
templates = "templates"

[nav]
nested = true
toc    = true
